// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/inventory/inventory.proto

package go_micro_srv_inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{0}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

// our example Supplier data
type Supplier struct {
	SupplierId           int32                `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	NameEn               string               `protobuf:"bytes,2,opt,name=nameEn,proto3" json:"nameEn,omitempty"`
	NameAr               string               `protobuf:"bytes,3,opt,name=nameAr,proto3" json:"nameAr,omitempty"`
	CreateAt             string               `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             string               `protobuf:"bytes,5,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	CreateBy             string               `protobuf:"bytes,6,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy             string               `protobuf:"bytes,7,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	ApprovedBy           string               `protobuf:"bytes,8,opt,name=approvedBy,proto3" json:"approvedBy,omitempty"`
	ApproveDate          string               `protobuf:"bytes,9,opt,name=approveDate,proto3" json:"approveDate,omitempty"`
	Class                string               `protobuf:"bytes,10,opt,name=class,proto3" json:"class,omitempty"`
	OEM                  string               `protobuf:"bytes,11,opt,name=OEM,proto3" json:"OEM,omitempty"`
	Exclusive            string               `protobuf:"bytes,12,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	Payments             string               `protobuf:"bytes,13,opt,name=payments,proto3" json:"payments,omitempty"`
	Days                 int32                `protobuf:"varint,14,opt,name=days,proto3" json:"days,omitempty"`
	Brands               []string             `protobuf:"bytes,15,rep,name=brands,proto3" json:"brands,omitempty"`
	AgreementType        string               `protobuf:"bytes,16,opt,name=agreementType,proto3" json:"agreementType,omitempty"`
	StartDate            string               `protobuf:"bytes,17,opt,name=startDate,proto3" json:"startDate,omitempty"`
	ExpiryDate           string               `protobuf:"bytes,18,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	Renewal              string               `protobuf:"bytes,19,opt,name=renewal,proto3" json:"renewal,omitempty"`
	AgreementPDF         string               `protobuf:"bytes,20,opt,name=agreementPDF,proto3" json:"agreementPDF,omitempty"`
	Contacts             []*Supplier_Contacts `protobuf:"bytes,21,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Supplier) Reset()         { *m = Supplier{} }
func (m *Supplier) String() string { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()    {}
func (*Supplier) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{1}
}

func (m *Supplier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supplier.Unmarshal(m, b)
}
func (m *Supplier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supplier.Marshal(b, m, deterministic)
}
func (m *Supplier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supplier.Merge(m, src)
}
func (m *Supplier) XXX_Size() int {
	return xxx_messageInfo_Supplier.Size(m)
}
func (m *Supplier) XXX_DiscardUnknown() {
	xxx_messageInfo_Supplier.DiscardUnknown(m)
}

var xxx_messageInfo_Supplier proto.InternalMessageInfo

func (m *Supplier) GetSupplierId() int32 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *Supplier) GetNameEn() string {
	if m != nil {
		return m.NameEn
	}
	return ""
}

func (m *Supplier) GetNameAr() string {
	if m != nil {
		return m.NameAr
	}
	return ""
}

func (m *Supplier) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *Supplier) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *Supplier) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *Supplier) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *Supplier) GetApprovedBy() string {
	if m != nil {
		return m.ApprovedBy
	}
	return ""
}

func (m *Supplier) GetApproveDate() string {
	if m != nil {
		return m.ApproveDate
	}
	return ""
}

func (m *Supplier) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Supplier) GetOEM() string {
	if m != nil {
		return m.OEM
	}
	return ""
}

func (m *Supplier) GetExclusive() string {
	if m != nil {
		return m.Exclusive
	}
	return ""
}

func (m *Supplier) GetPayments() string {
	if m != nil {
		return m.Payments
	}
	return ""
}

func (m *Supplier) GetDays() int32 {
	if m != nil {
		return m.Days
	}
	return 0
}

func (m *Supplier) GetBrands() []string {
	if m != nil {
		return m.Brands
	}
	return nil
}

func (m *Supplier) GetAgreementType() string {
	if m != nil {
		return m.AgreementType
	}
	return ""
}

func (m *Supplier) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Supplier) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *Supplier) GetRenewal() string {
	if m != nil {
		return m.Renewal
	}
	return ""
}

func (m *Supplier) GetAgreementPDF() string {
	if m != nil {
		return m.AgreementPDF
	}
	return ""
}

func (m *Supplier) GetContacts() []*Supplier_Contacts {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type Supplier_Contacts struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Tel                  string   `protobuf:"bytes,3,opt,name=tel,proto3" json:"tel,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Web                  string   `protobuf:"bytes,6,opt,name=web,proto3" json:"web,omitempty"`
	Designations         string   `protobuf:"bytes,7,opt,name=designations,proto3" json:"designations,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Supplier_Contacts) Reset()         { *m = Supplier_Contacts{} }
func (m *Supplier_Contacts) String() string { return proto.CompactTextString(m) }
func (*Supplier_Contacts) ProtoMessage()    {}
func (*Supplier_Contacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{1, 0}
}

func (m *Supplier_Contacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supplier_Contacts.Unmarshal(m, b)
}
func (m *Supplier_Contacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supplier_Contacts.Marshal(b, m, deterministic)
}
func (m *Supplier_Contacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supplier_Contacts.Merge(m, src)
}
func (m *Supplier_Contacts) XXX_Size() int {
	return xxx_messageInfo_Supplier_Contacts.Size(m)
}
func (m *Supplier_Contacts) XXX_DiscardUnknown() {
	xxx_messageInfo_Supplier_Contacts.DiscardUnknown(m)
}

var xxx_messageInfo_Supplier_Contacts proto.InternalMessageInfo

func (m *Supplier_Contacts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supplier_Contacts) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Supplier_Contacts) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *Supplier_Contacts) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Supplier_Contacts) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Supplier_Contacts) GetWeb() string {
	if m != nil {
		return m.Web
	}
	return ""
}

func (m *Supplier_Contacts) GetDesignations() string {
	if m != nil {
		return m.Designations
	}
	return ""
}

// send id in the required to read
type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// return one  Supplier //not used
type SupplierResponse struct {
	Suppliers            []*Supplier `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SupplierResponse) Reset()         { *m = SupplierResponse{} }
func (m *SupplierResponse) String() string { return proto.CompactTextString(m) }
func (*SupplierResponse) ProtoMessage()    {}
func (*SupplierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{3}
}

func (m *SupplierResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplierResponse.Unmarshal(m, b)
}
func (m *SupplierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplierResponse.Marshal(b, m, deterministic)
}
func (m *SupplierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplierResponse.Merge(m, src)
}
func (m *SupplierResponse) XXX_Size() int {
	return xxx_messageInfo_SupplierResponse.Size(m)
}
func (m *SupplierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SupplierResponse proto.InternalMessageInfo

func (m *SupplierResponse) GetSuppliers() []*Supplier {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

type Confirm struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirm) Reset()         { *m = Confirm{} }
func (m *Confirm) String() string { return proto.CompactTextString(m) }
func (*Confirm) ProtoMessage()    {}
func (*Confirm) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{4}
}

func (m *Confirm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirm.Unmarshal(m, b)
}
func (m *Confirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirm.Marshal(b, m, deterministic)
}
func (m *Confirm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirm.Merge(m, src)
}
func (m *Confirm) XXX_Size() int {
	return xxx_messageInfo_Confirm.Size(m)
}
func (m *Confirm) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirm.DiscardUnknown(m)
}

var xxx_messageInfo_Confirm proto.InternalMessageInfo

func (m *Confirm) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Confirm) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Filter struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Search               string   `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{5}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *Filter) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

// return all Supplier that satisfy filter
type SupplierBigData struct {
	Suppliers            []*Supplier `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SupplierBigData) Reset()         { *m = SupplierBigData{} }
func (m *SupplierBigData) String() string { return proto.CompactTextString(m) }
func (*SupplierBigData) ProtoMessage()    {}
func (*SupplierBigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{6}
}

func (m *SupplierBigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplierBigData.Unmarshal(m, b)
}
func (m *SupplierBigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplierBigData.Marshal(b, m, deterministic)
}
func (m *SupplierBigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplierBigData.Merge(m, src)
}
func (m *SupplierBigData) XXX_Size() int {
	return xxx_messageInfo_SupplierBigData.Size(m)
}
func (m *SupplierBigData) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplierBigData.DiscardUnknown(m)
}

var xxx_messageInfo_SupplierBigData proto.InternalMessageInfo

func (m *SupplierBigData) GetSuppliers() []*Supplier {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

//Product Owner
type PurchaseOrder struct {
	Po                   int32                  `protobuf:"varint,1,opt,name=po,proto3" json:"po,omitempty"`
	CreateAt             string                 `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             string                 `protobuf:"bytes,3,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	CreateBy             string                 `protobuf:"bytes,4,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy             string                 `protobuf:"bytes,5,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Supplier             string                 `protobuf:"bytes,6,opt,name=supplier,proto3" json:"supplier,omitempty"`
	BatchID              int32                  `protobuf:"varint,7,opt,name=batchID,proto3" json:"batchID,omitempty"`
	BatchDate            string                 `protobuf:"bytes,8,opt,name=batchDate,proto3" json:"batchDate,omitempty"`
	Desc                 string                 `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	Items                []*PurchaseOrder_Items `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PurchaseOrder) Reset()         { *m = PurchaseOrder{} }
func (m *PurchaseOrder) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrder) ProtoMessage()    {}
func (*PurchaseOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{7}
}

func (m *PurchaseOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrder.Unmarshal(m, b)
}
func (m *PurchaseOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrder.Marshal(b, m, deterministic)
}
func (m *PurchaseOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrder.Merge(m, src)
}
func (m *PurchaseOrder) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrder.Size(m)
}
func (m *PurchaseOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrder proto.InternalMessageInfo

func (m *PurchaseOrder) GetPo() int32 {
	if m != nil {
		return m.Po
	}
	return 0
}

func (m *PurchaseOrder) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *PurchaseOrder) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *PurchaseOrder) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *PurchaseOrder) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *PurchaseOrder) GetSupplier() string {
	if m != nil {
		return m.Supplier
	}
	return ""
}

func (m *PurchaseOrder) GetBatchID() int32 {
	if m != nil {
		return m.BatchID
	}
	return 0
}

func (m *PurchaseOrder) GetBatchDate() string {
	if m != nil {
		return m.BatchDate
	}
	return ""
}

func (m *PurchaseOrder) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *PurchaseOrder) GetItems() []*PurchaseOrder_Items {
	if m != nil {
		return m.Items
	}
	return nil
}

type PurchaseOrder_Items struct {
	ProductID            int32    `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Qty                  int32    `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseOrder_Items) Reset()         { *m = PurchaseOrder_Items{} }
func (m *PurchaseOrder_Items) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrder_Items) ProtoMessage()    {}
func (*PurchaseOrder_Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{7, 0}
}

func (m *PurchaseOrder_Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrder_Items.Unmarshal(m, b)
}
func (m *PurchaseOrder_Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrder_Items.Marshal(b, m, deterministic)
}
func (m *PurchaseOrder_Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrder_Items.Merge(m, src)
}
func (m *PurchaseOrder_Items) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrder_Items.Size(m)
}
func (m *PurchaseOrder_Items) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrder_Items.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrder_Items proto.InternalMessageInfo

func (m *PurchaseOrder_Items) GetProductID() int32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *PurchaseOrder_Items) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *PurchaseOrder_Items) GetQty() int32 {
	if m != nil {
		return m.Qty
	}
	return 0
}

func (m *PurchaseOrder_Items) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PurchaseOrderResponse struct {
	PurchaseOrder        *PurchaseOrder `protobuf:"bytes,1,opt,name=purchaseOrder,proto3" json:"purchaseOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PurchaseOrderResponse) Reset()         { *m = PurchaseOrderResponse{} }
func (m *PurchaseOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrderResponse) ProtoMessage()    {}
func (*PurchaseOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{8}
}

func (m *PurchaseOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrderResponse.Unmarshal(m, b)
}
func (m *PurchaseOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrderResponse.Marshal(b, m, deterministic)
}
func (m *PurchaseOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrderResponse.Merge(m, src)
}
func (m *PurchaseOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrderResponse.Size(m)
}
func (m *PurchaseOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrderResponse proto.InternalMessageInfo

func (m *PurchaseOrderResponse) GetPurchaseOrder() *PurchaseOrder {
	if m != nil {
		return m.PurchaseOrder
	}
	return nil
}

// return all DeliveryNote that satisfy filter
type PurchaseOrderBigData struct {
	PurchaseOrders       []*PurchaseOrder `protobuf:"bytes,1,rep,name=purchaseOrders,proto3" json:"purchaseOrders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PurchaseOrderBigData) Reset()         { *m = PurchaseOrderBigData{} }
func (m *PurchaseOrderBigData) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrderBigData) ProtoMessage()    {}
func (*PurchaseOrderBigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{9}
}

func (m *PurchaseOrderBigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrderBigData.Unmarshal(m, b)
}
func (m *PurchaseOrderBigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrderBigData.Marshal(b, m, deterministic)
}
func (m *PurchaseOrderBigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrderBigData.Merge(m, src)
}
func (m *PurchaseOrderBigData) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrderBigData.Size(m)
}
func (m *PurchaseOrderBigData) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrderBigData.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrderBigData proto.InternalMessageInfo

func (m *PurchaseOrderBigData) GetPurchaseOrders() []*PurchaseOrder {
	if m != nil {
		return m.PurchaseOrders
	}
	return nil
}

//Delivery Note
type DeliveryNote struct {
	DeliveryId           int32                 `protobuf:"varint,1,opt,name=deliveryId,proto3" json:"deliveryId,omitempty"`
	RefPO                int32                 `protobuf:"varint,2,opt,name=refPO,proto3" json:"refPO,omitempty"`
	CreatedAt            string                `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdateAt             string                `protobuf:"bytes,4,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	CreatedBy            string                `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdateBy             string                `protobuf:"bytes,6,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Note                 string                `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Items                []*DeliveryNote_Items `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeliveryNote) Reset()         { *m = DeliveryNote{} }
func (m *DeliveryNote) String() string { return proto.CompactTextString(m) }
func (*DeliveryNote) ProtoMessage()    {}
func (*DeliveryNote) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{10}
}

func (m *DeliveryNote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryNote.Unmarshal(m, b)
}
func (m *DeliveryNote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryNote.Marshal(b, m, deterministic)
}
func (m *DeliveryNote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryNote.Merge(m, src)
}
func (m *DeliveryNote) XXX_Size() int {
	return xxx_messageInfo_DeliveryNote.Size(m)
}
func (m *DeliveryNote) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryNote.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryNote proto.InternalMessageInfo

func (m *DeliveryNote) GetDeliveryId() int32 {
	if m != nil {
		return m.DeliveryId
	}
	return 0
}

func (m *DeliveryNote) GetRefPO() int32 {
	if m != nil {
		return m.RefPO
	}
	return 0
}

func (m *DeliveryNote) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *DeliveryNote) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *DeliveryNote) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DeliveryNote) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *DeliveryNote) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *DeliveryNote) GetItems() []*DeliveryNote_Items {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeliveryNote_Items struct {
	ProductId            int32    `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	OrderedQty           int32    `protobuf:"varint,3,opt,name=orderedQty,proto3" json:"orderedQty,omitempty"`
	RecviedQty           int32    `protobuf:"varint,4,opt,name=recviedQty,proto3" json:"recviedQty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryNote_Items) Reset()         { *m = DeliveryNote_Items{} }
func (m *DeliveryNote_Items) String() string { return proto.CompactTextString(m) }
func (*DeliveryNote_Items) ProtoMessage()    {}
func (*DeliveryNote_Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{10, 0}
}

func (m *DeliveryNote_Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryNote_Items.Unmarshal(m, b)
}
func (m *DeliveryNote_Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryNote_Items.Marshal(b, m, deterministic)
}
func (m *DeliveryNote_Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryNote_Items.Merge(m, src)
}
func (m *DeliveryNote_Items) XXX_Size() int {
	return xxx_messageInfo_DeliveryNote_Items.Size(m)
}
func (m *DeliveryNote_Items) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryNote_Items.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryNote_Items proto.InternalMessageInfo

func (m *DeliveryNote_Items) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *DeliveryNote_Items) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *DeliveryNote_Items) GetOrderedQty() int32 {
	if m != nil {
		return m.OrderedQty
	}
	return 0
}

func (m *DeliveryNote_Items) GetRecviedQty() int32 {
	if m != nil {
		return m.RecviedQty
	}
	return 0
}

type DeliveryNoteResponse struct {
	DeliveryNote         *DeliveryNote `protobuf:"bytes,1,opt,name=deliveryNote,proto3" json:"deliveryNote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeliveryNoteResponse) Reset()         { *m = DeliveryNoteResponse{} }
func (m *DeliveryNoteResponse) String() string { return proto.CompactTextString(m) }
func (*DeliveryNoteResponse) ProtoMessage()    {}
func (*DeliveryNoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{11}
}

func (m *DeliveryNoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryNoteResponse.Unmarshal(m, b)
}
func (m *DeliveryNoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryNoteResponse.Marshal(b, m, deterministic)
}
func (m *DeliveryNoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryNoteResponse.Merge(m, src)
}
func (m *DeliveryNoteResponse) XXX_Size() int {
	return xxx_messageInfo_DeliveryNoteResponse.Size(m)
}
func (m *DeliveryNoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryNoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryNoteResponse proto.InternalMessageInfo

func (m *DeliveryNoteResponse) GetDeliveryNote() *DeliveryNote {
	if m != nil {
		return m.DeliveryNote
	}
	return nil
}

// return all DeliveryNote that satisfy filter
type DeliveryNoteBigData struct {
	DeliveryNotes        []*DeliveryNote `protobuf:"bytes,1,rep,name=deliveryNotes,proto3" json:"deliveryNotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeliveryNoteBigData) Reset()         { *m = DeliveryNoteBigData{} }
func (m *DeliveryNoteBigData) String() string { return proto.CompactTextString(m) }
func (*DeliveryNoteBigData) ProtoMessage()    {}
func (*DeliveryNoteBigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{12}
}

func (m *DeliveryNoteBigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryNoteBigData.Unmarshal(m, b)
}
func (m *DeliveryNoteBigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryNoteBigData.Marshal(b, m, deterministic)
}
func (m *DeliveryNoteBigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryNoteBigData.Merge(m, src)
}
func (m *DeliveryNoteBigData) XXX_Size() int {
	return xxx_messageInfo_DeliveryNoteBigData.Size(m)
}
func (m *DeliveryNoteBigData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryNoteBigData.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryNoteBigData proto.InternalMessageInfo

func (m *DeliveryNoteBigData) GetDeliveryNotes() []*DeliveryNote {
	if m != nil {
		return m.DeliveryNotes
	}
	return nil
}

//Master stock
type MasterStock struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Po                   int32                `protobuf:"varint,2,opt,name=po,proto3" json:"po,omitempty"`
	DeliveryNote         int32                `protobuf:"varint,3,opt,name=deliveryNote,proto3" json:"deliveryNote,omitempty"`
	Total                int32                `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Productid            int32                `protobuf:"varint,5,opt,name=productid,proto3" json:"productid,omitempty"`
	SupplierId           int32                `protobuf:"varint,6,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	Items                []*MasterStock_Items `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MasterStock) Reset()         { *m = MasterStock{} }
func (m *MasterStock) String() string { return proto.CompactTextString(m) }
func (*MasterStock) ProtoMessage()    {}
func (*MasterStock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{13}
}

func (m *MasterStock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterStock.Unmarshal(m, b)
}
func (m *MasterStock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterStock.Marshal(b, m, deterministic)
}
func (m *MasterStock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterStock.Merge(m, src)
}
func (m *MasterStock) XXX_Size() int {
	return xxx_messageInfo_MasterStock.Size(m)
}
func (m *MasterStock) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterStock.DiscardUnknown(m)
}

var xxx_messageInfo_MasterStock proto.InternalMessageInfo

func (m *MasterStock) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MasterStock) GetPo() int32 {
	if m != nil {
		return m.Po
	}
	return 0
}

func (m *MasterStock) GetDeliveryNote() int32 {
	if m != nil {
		return m.DeliveryNote
	}
	return 0
}

func (m *MasterStock) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MasterStock) GetProductid() int32 {
	if m != nil {
		return m.Productid
	}
	return 0
}

func (m *MasterStock) GetSupplierId() int32 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *MasterStock) GetItems() []*MasterStock_Items {
	if m != nil {
		return m.Items
	}
	return nil
}

type MasterStock_Items struct {
	Serial               float64  `protobuf:"fixed64,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Pin                  string   `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,3,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterStock_Items) Reset()         { *m = MasterStock_Items{} }
func (m *MasterStock_Items) String() string { return proto.CompactTextString(m) }
func (*MasterStock_Items) ProtoMessage()    {}
func (*MasterStock_Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{13, 0}
}

func (m *MasterStock_Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterStock_Items.Unmarshal(m, b)
}
func (m *MasterStock_Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterStock_Items.Marshal(b, m, deterministic)
}
func (m *MasterStock_Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterStock_Items.Merge(m, src)
}
func (m *MasterStock_Items) XXX_Size() int {
	return xxx_messageInfo_MasterStock_Items.Size(m)
}
func (m *MasterStock_Items) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterStock_Items.DiscardUnknown(m)
}

var xxx_messageInfo_MasterStock_Items proto.InternalMessageInfo

func (m *MasterStock_Items) GetSerial() float64 {
	if m != nil {
		return m.Serial
	}
	return 0
}

func (m *MasterStock_Items) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *MasterStock_Items) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *MasterStock_Items) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MasterStockResponse struct {
	MasterStock          *MasterStock `protobuf:"bytes,1,opt,name=masterStock,proto3" json:"masterStock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MasterStockResponse) Reset()         { *m = MasterStockResponse{} }
func (m *MasterStockResponse) String() string { return proto.CompactTextString(m) }
func (*MasterStockResponse) ProtoMessage()    {}
func (*MasterStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{14}
}

func (m *MasterStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterStockResponse.Unmarshal(m, b)
}
func (m *MasterStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterStockResponse.Marshal(b, m, deterministic)
}
func (m *MasterStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterStockResponse.Merge(m, src)
}
func (m *MasterStockResponse) XXX_Size() int {
	return xxx_messageInfo_MasterStockResponse.Size(m)
}
func (m *MasterStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterStockResponse proto.InternalMessageInfo

func (m *MasterStockResponse) GetMasterStock() *MasterStock {
	if m != nil {
		return m.MasterStock
	}
	return nil
}

// return all MasterStock that satisfy filter
type MasterStockBigData struct {
	MasterStocks         []*MasterStock `protobuf:"bytes,1,rep,name=masterStocks,proto3" json:"masterStocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MasterStockBigData) Reset()         { *m = MasterStockBigData{} }
func (m *MasterStockBigData) String() string { return proto.CompactTextString(m) }
func (*MasterStockBigData) ProtoMessage()    {}
func (*MasterStockBigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{15}
}

func (m *MasterStockBigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterStockBigData.Unmarshal(m, b)
}
func (m *MasterStockBigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterStockBigData.Marshal(b, m, deterministic)
}
func (m *MasterStockBigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterStockBigData.Merge(m, src)
}
func (m *MasterStockBigData) XXX_Size() int {
	return xxx_messageInfo_MasterStockBigData.Size(m)
}
func (m *MasterStockBigData) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterStockBigData.DiscardUnknown(m)
}

var xxx_messageInfo_MasterStockBigData proto.InternalMessageInfo

func (m *MasterStockBigData) GetMasterStocks() []*MasterStock {
	if m != nil {
		return m.MasterStocks
	}
	return nil
}

//Stock pool
type StockPool struct {
	PoolId               int32    `protobuf:"varint,1,opt,name=poolId,proto3" json:"poolId,omitempty"`
	CreateAt             string   `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             string   `protobuf:"bytes,3,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	CreateBy             string   `protobuf:"bytes,4,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy             string   `protobuf:"bytes,5,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	StartSerial          int32    `protobuf:"varint,6,opt,name=startSerial,proto3" json:"startSerial,omitempty"`
	EndSerial            int32    `protobuf:"varint,7,opt,name=endSerial,proto3" json:"endSerial,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Total                int32    `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	TotalSold            int32    `protobuf:"varint,10,opt,name=totalSold,proto3" json:"totalSold,omitempty"`
	Remaining            int32    `protobuf:"varint,11,opt,name=remaining,proto3" json:"remaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPool) Reset()         { *m = StockPool{} }
func (m *StockPool) String() string { return proto.CompactTextString(m) }
func (*StockPool) ProtoMessage()    {}
func (*StockPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{16}
}

func (m *StockPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPool.Unmarshal(m, b)
}
func (m *StockPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPool.Marshal(b, m, deterministic)
}
func (m *StockPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPool.Merge(m, src)
}
func (m *StockPool) XXX_Size() int {
	return xxx_messageInfo_StockPool.Size(m)
}
func (m *StockPool) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPool.DiscardUnknown(m)
}

var xxx_messageInfo_StockPool proto.InternalMessageInfo

func (m *StockPool) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *StockPool) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *StockPool) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *StockPool) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *StockPool) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func (m *StockPool) GetStartSerial() int32 {
	if m != nil {
		return m.StartSerial
	}
	return 0
}

func (m *StockPool) GetEndSerial() int32 {
	if m != nil {
		return m.EndSerial
	}
	return 0
}

func (m *StockPool) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StockPool) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *StockPool) GetTotalSold() int32 {
	if m != nil {
		return m.TotalSold
	}
	return 0
}

func (m *StockPool) GetRemaining() int32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

type StockPoolResponse struct {
	StockPool            *StockPool `protobuf:"bytes,1,opt,name=stockPool,proto3" json:"stockPool,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StockPoolResponse) Reset()         { *m = StockPoolResponse{} }
func (m *StockPoolResponse) String() string { return proto.CompactTextString(m) }
func (*StockPoolResponse) ProtoMessage()    {}
func (*StockPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{17}
}

func (m *StockPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPoolResponse.Unmarshal(m, b)
}
func (m *StockPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPoolResponse.Marshal(b, m, deterministic)
}
func (m *StockPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPoolResponse.Merge(m, src)
}
func (m *StockPoolResponse) XXX_Size() int {
	return xxx_messageInfo_StockPoolResponse.Size(m)
}
func (m *StockPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockPoolResponse proto.InternalMessageInfo

func (m *StockPoolResponse) GetStockPool() *StockPool {
	if m != nil {
		return m.StockPool
	}
	return nil
}

// return all ShippingEvent that satisfy filter
type StockPoolBigData struct {
	StockPools           []*StockPool `protobuf:"bytes,1,rep,name=stockPools,proto3" json:"stockPools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StockPoolBigData) Reset()         { *m = StockPoolBigData{} }
func (m *StockPoolBigData) String() string { return proto.CompactTextString(m) }
func (*StockPoolBigData) ProtoMessage()    {}
func (*StockPoolBigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{18}
}

func (m *StockPoolBigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPoolBigData.Unmarshal(m, b)
}
func (m *StockPoolBigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPoolBigData.Marshal(b, m, deterministic)
}
func (m *StockPoolBigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPoolBigData.Merge(m, src)
}
func (m *StockPoolBigData) XXX_Size() int {
	return xxx_messageInfo_StockPoolBigData.Size(m)
}
func (m *StockPoolBigData) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPoolBigData.DiscardUnknown(m)
}

var xxx_messageInfo_StockPoolBigData proto.InternalMessageInfo

func (m *StockPoolBigData) GetStockPools() []*StockPool {
	if m != nil {
		return m.StockPools
	}
	return nil
}

//Shipping Event
type ShippingEvent struct {
	OrderId              int32    `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	CreateAt             string   `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	ItemType             string   `protobuf:"bytes,3,opt,name=itemType,proto3" json:"itemType,omitempty"`
	ItemsSerial          int32    `protobuf:"varint,4,opt,name=itemsSerial,proto3" json:"itemsSerial,omitempty"`
	Events               string   `protobuf:"bytes,5,opt,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShippingEvent) Reset()         { *m = ShippingEvent{} }
func (m *ShippingEvent) String() string { return proto.CompactTextString(m) }
func (*ShippingEvent) ProtoMessage()    {}
func (*ShippingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{19}
}

func (m *ShippingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShippingEvent.Unmarshal(m, b)
}
func (m *ShippingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShippingEvent.Marshal(b, m, deterministic)
}
func (m *ShippingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShippingEvent.Merge(m, src)
}
func (m *ShippingEvent) XXX_Size() int {
	return xxx_messageInfo_ShippingEvent.Size(m)
}
func (m *ShippingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ShippingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ShippingEvent proto.InternalMessageInfo

func (m *ShippingEvent) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ShippingEvent) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *ShippingEvent) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *ShippingEvent) GetItemsSerial() int32 {
	if m != nil {
		return m.ItemsSerial
	}
	return 0
}

func (m *ShippingEvent) GetEvents() string {
	if m != nil {
		return m.Events
	}
	return ""
}

type ShippingEventResponse struct {
	ShippingEvent        *ShippingEvent `protobuf:"bytes,1,opt,name=shippingEvent,proto3" json:"shippingEvent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShippingEventResponse) Reset()         { *m = ShippingEventResponse{} }
func (m *ShippingEventResponse) String() string { return proto.CompactTextString(m) }
func (*ShippingEventResponse) ProtoMessage()    {}
func (*ShippingEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{20}
}

func (m *ShippingEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShippingEventResponse.Unmarshal(m, b)
}
func (m *ShippingEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShippingEventResponse.Marshal(b, m, deterministic)
}
func (m *ShippingEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShippingEventResponse.Merge(m, src)
}
func (m *ShippingEventResponse) XXX_Size() int {
	return xxx_messageInfo_ShippingEventResponse.Size(m)
}
func (m *ShippingEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShippingEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShippingEventResponse proto.InternalMessageInfo

func (m *ShippingEventResponse) GetShippingEvent() *ShippingEvent {
	if m != nil {
		return m.ShippingEvent
	}
	return nil
}

// return all ShippingEvent that satisfy filter
type ShippingEventBigData struct {
	ShippingEvents       []*ShippingEvent `protobuf:"bytes,1,rep,name=shippingEvents,proto3" json:"shippingEvents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ShippingEventBigData) Reset()         { *m = ShippingEventBigData{} }
func (m *ShippingEventBigData) String() string { return proto.CompactTextString(m) }
func (*ShippingEventBigData) ProtoMessage()    {}
func (*ShippingEventBigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d77ba5e53e1c0527, []int{21}
}

func (m *ShippingEventBigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShippingEventBigData.Unmarshal(m, b)
}
func (m *ShippingEventBigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShippingEventBigData.Marshal(b, m, deterministic)
}
func (m *ShippingEventBigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShippingEventBigData.Merge(m, src)
}
func (m *ShippingEventBigData) XXX_Size() int {
	return xxx_messageInfo_ShippingEventBigData.Size(m)
}
func (m *ShippingEventBigData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShippingEventBigData.DiscardUnknown(m)
}

var xxx_messageInfo_ShippingEventBigData proto.InternalMessageInfo

func (m *ShippingEventBigData) GetShippingEvents() []*ShippingEvent {
	if m != nil {
		return m.ShippingEvents
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyRequest)(nil), "go.micro.srv.inventory.EmptyRequest")
	proto.RegisterType((*Supplier)(nil), "go.micro.srv.inventory.Supplier")
	proto.RegisterType((*Supplier_Contacts)(nil), "go.micro.srv.inventory.Supplier.Contacts")
	proto.RegisterType((*Request)(nil), "go.micro.srv.inventory.Request")
	proto.RegisterType((*SupplierResponse)(nil), "go.micro.srv.inventory.SupplierResponse")
	proto.RegisterType((*Confirm)(nil), "go.micro.srv.inventory.Confirm")
	proto.RegisterType((*Filter)(nil), "go.micro.srv.inventory.Filter")
	proto.RegisterType((*SupplierBigData)(nil), "go.micro.srv.inventory.SupplierBigData")
	proto.RegisterType((*PurchaseOrder)(nil), "go.micro.srv.inventory.PurchaseOrder")
	proto.RegisterType((*PurchaseOrder_Items)(nil), "go.micro.srv.inventory.PurchaseOrder.Items")
	proto.RegisterType((*PurchaseOrderResponse)(nil), "go.micro.srv.inventory.PurchaseOrderResponse")
	proto.RegisterType((*PurchaseOrderBigData)(nil), "go.micro.srv.inventory.PurchaseOrderBigData")
	proto.RegisterType((*DeliveryNote)(nil), "go.micro.srv.inventory.DeliveryNote")
	proto.RegisterType((*DeliveryNote_Items)(nil), "go.micro.srv.inventory.DeliveryNote.Items")
	proto.RegisterType((*DeliveryNoteResponse)(nil), "go.micro.srv.inventory.DeliveryNoteResponse")
	proto.RegisterType((*DeliveryNoteBigData)(nil), "go.micro.srv.inventory.DeliveryNoteBigData")
	proto.RegisterType((*MasterStock)(nil), "go.micro.srv.inventory.MasterStock")
	proto.RegisterType((*MasterStock_Items)(nil), "go.micro.srv.inventory.MasterStock.Items")
	proto.RegisterType((*MasterStockResponse)(nil), "go.micro.srv.inventory.MasterStockResponse")
	proto.RegisterType((*MasterStockBigData)(nil), "go.micro.srv.inventory.MasterStockBigData")
	proto.RegisterType((*StockPool)(nil), "go.micro.srv.inventory.StockPool")
	proto.RegisterType((*StockPoolResponse)(nil), "go.micro.srv.inventory.StockPoolResponse")
	proto.RegisterType((*StockPoolBigData)(nil), "go.micro.srv.inventory.StockPoolBigData")
	proto.RegisterType((*ShippingEvent)(nil), "go.micro.srv.inventory.ShippingEvent")
	proto.RegisterType((*ShippingEventResponse)(nil), "go.micro.srv.inventory.ShippingEventResponse")
	proto.RegisterType((*ShippingEventBigData)(nil), "go.micro.srv.inventory.ShippingEventBigData")
}

func init() { proto.RegisterFile("proto/inventory/inventory.proto", fileDescriptor_d77ba5e53e1c0527) }

var fileDescriptor_d77ba5e53e1c0527 = []byte{
	// 1705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x5d, 0x72, 0xdb, 0x46,
	0x12, 0x36, 0x49, 0x51, 0x22, 0x5b, 0xff, 0x90, 0xec, 0xc2, 0xb2, 0xb6, 0x6c, 0x2d, 0xd6, 0x5b,
	0xab, 0xb5, 0xb7, 0xb8, 0x55, 0xf6, 0xcb, 0x3e, 0xad, 0x57, 0xb2, 0x64, 0xaf, 0x36, 0xe5, 0x58,
	0x86, 0xac, 0x72, 0x52, 0xb6, 0x93, 0x40, 0xc0, 0x88, 0x42, 0x19, 0x04, 0xe0, 0x01, 0x44, 0x9b,
	0x47, 0xc8, 0x19, 0x52, 0xb9, 0x42, 0x9e, 0xf2, 0x9a, 0x43, 0xe4, 0x08, 0xb9, 0x49, 0xaa, 0xe7,
	0x07, 0x33, 0x43, 0x8b, 0xc2, 0xd0, 0xb6, 0xf2, 0x36, 0xdd, 0xcd, 0xee, 0x9e, 0xe9, 0xfe, 0xa6,
	0xe7, 0x43, 0x11, 0x6e, 0xe5, 0x34, 0x2b, 0xb3, 0x7f, 0xc5, 0xe9, 0x88, 0xa4, 0x65, 0x46, 0xc7,
	0x6a, 0xd5, 0x67, 0x16, 0xe7, 0xc6, 0x20, 0xeb, 0x0f, 0xe3, 0x90, 0x66, 0xfd, 0x82, 0x8e, 0xfa,
	0x95, 0xd5, 0x5b, 0x81, 0xa5, 0xfd, 0x61, 0x5e, 0x8e, 0x7d, 0xf2, 0xf6, 0x9c, 0x14, 0xa5, 0xf7,
	0xf3, 0x3c, 0x74, 0x8e, 0xce, 0xf3, 0x3c, 0x89, 0x09, 0x75, 0x6e, 0x02, 0x14, 0x62, 0x7d, 0x10,
	0xb9, 0x8d, 0xad, 0xc6, 0x76, 0xdb, 0xd7, 0x34, 0xce, 0x0d, 0x98, 0x4f, 0x83, 0x21, 0xd9, 0x4f,
	0xdd, 0xe6, 0x56, 0x63, 0xbb, 0xeb, 0x0b, 0x49, 0xea, 0x77, 0xa8, 0xdb, 0x52, 0xfa, 0x1d, 0xea,
	0xf4, 0xa0, 0x13, 0x52, 0x12, 0x94, 0x64, 0xa7, 0x74, 0xe7, 0x98, 0xa5, 0x92, 0xd1, 0x76, 0x9e,
	0x47, 0xdc, 0xd6, 0xe6, 0x36, 0x29, 0x2b, 0xbf, 0xdd, 0xb1, 0x3b, 0xaf, 0xfb, 0xed, 0x8e, 0x95,
	0xdf, 0xee, 0xd8, 0x5d, 0xd0, 0xfd, 0x76, 0xc7, 0xb8, 0xff, 0x20, 0xcf, 0x69, 0x36, 0x22, 0xd1,
	0xee, 0xd8, 0xed, 0x30, 0xab, 0xa6, 0x71, 0xb6, 0x60, 0x51, 0x48, 0x7b, 0x41, 0x49, 0xdc, 0x2e,
	0xfb, 0x81, 0xae, 0x72, 0x36, 0xa1, 0x1d, 0x26, 0x41, 0x51, 0xb8, 0xc0, 0x6c, 0x5c, 0x70, 0xd6,
	0xa0, 0xf5, 0x74, 0xff, 0x89, 0xbb, 0xc8, 0x74, 0xb8, 0x74, 0xfe, 0x0c, 0x5d, 0xf2, 0x3e, 0x4c,
	0xce, 0x8b, 0x78, 0x44, 0xdc, 0x25, 0xa6, 0x57, 0x0a, 0xdc, 0x63, 0x1e, 0x8c, 0x87, 0x24, 0x2d,
	0x0b, 0x77, 0x99, 0xef, 0x51, 0xca, 0x8e, 0x03, 0x73, 0x51, 0x30, 0x2e, 0xdc, 0x15, 0x56, 0x5d,
	0xb6, 0xc6, 0xfa, 0x9d, 0xd0, 0x20, 0x8d, 0x0a, 0x77, 0x75, 0xab, 0x85, 0xf5, 0xe3, 0x92, 0x73,
	0x1b, 0x96, 0x83, 0x01, 0x25, 0x04, 0x3d, 0x9f, 0x8f, 0x73, 0xe2, 0xae, 0xb1, 0x60, 0xa6, 0x12,
	0xf7, 0x52, 0x94, 0x01, 0x2d, 0xd9, 0x99, 0xd6, 0xf9, 0x5e, 0x2a, 0x05, 0xd6, 0x84, 0xbc, 0xcf,
	0x63, 0x3a, 0x66, 0x66, 0x87, 0xd7, 0x44, 0x69, 0x1c, 0x17, 0x16, 0x28, 0x49, 0xc9, 0xbb, 0x20,
	0x71, 0x37, 0x98, 0x51, 0x8a, 0x8e, 0x07, 0x4b, 0x55, 0xa2, 0xc3, 0xbd, 0x47, 0xee, 0x26, 0x33,
	0x1b, 0x3a, 0x67, 0x1f, 0x3a, 0x61, 0x96, 0x96, 0x41, 0x58, 0x16, 0xee, 0xf5, 0xad, 0xd6, 0xf6,
	0xe2, 0xbd, 0x7f, 0xf4, 0x2f, 0x46, 0x5e, 0x5f, 0xa2, 0xac, 0xff, 0x50, 0x38, 0xf8, 0x95, 0x6b,
	0xef, 0xa7, 0x06, 0x74, 0xa4, 0x1a, 0x2b, 0x84, 0xf8, 0x61, 0xf8, 0xeb, 0xfa, 0x6c, 0x8d, 0xbb,
	0x0c, 0xa2, 0x88, 0x92, 0xa2, 0x10, 0xd0, 0x93, 0x22, 0xf6, 0xa6, 0x24, 0x89, 0x00, 0x1e, 0x2e,
	0xb1, 0x9a, 0xc3, 0xec, 0x24, 0x4e, 0x88, 0xc0, 0x9c, 0x90, 0xb0, 0xb7, 0x64, 0x18, 0xc4, 0x89,
	0x80, 0x1b, 0x17, 0xd0, 0xff, 0x1d, 0x39, 0x11, 0x30, 0xc3, 0x25, 0x9e, 0x3b, 0x22, 0x45, 0x3c,
	0x48, 0x83, 0x32, 0xce, 0xd2, 0x42, 0xa0, 0xcc, 0xd0, 0x79, 0x7f, 0x82, 0x05, 0x71, 0x83, 0x9c,
	0x15, 0x68, 0xc6, 0x91, 0xd8, 0x6c, 0x33, 0x8e, 0x3c, 0x1f, 0xd6, 0xe4, 0x51, 0x7d, 0x52, 0xe4,
	0x59, 0x5a, 0x10, 0xe7, 0x3f, 0xd0, 0x95, 0xd7, 0xa8, 0x70, 0x1b, 0xac, 0x4e, 0x5b, 0x75, 0x75,
	0xf2, 0x95, 0x8b, 0x77, 0x1f, 0x16, 0x1e, 0x66, 0xe9, 0x69, 0x4c, 0x87, 0x78, 0xba, 0xa2, 0x0c,
	0xca, 0xf3, 0x42, 0xdc, 0x4f, 0x21, 0xe1, 0x39, 0x86, 0xc5, 0x40, 0x54, 0x07, 0x97, 0xde, 0xbf,
	0x61, 0xfe, 0x51, 0x9c, 0x94, 0x84, 0xa2, 0xcf, 0x29, 0x5b, 0x89, 0x6d, 0x0a, 0x89, 0xc5, 0x22,
	0x01, 0x0d, 0xcf, 0xe4, 0x7d, 0xe6, 0x92, 0xf7, 0x0c, 0x56, 0xe5, 0x2e, 0x76, 0xe3, 0xc1, 0x5e,
	0x50, 0x06, 0x9f, 0x7c, 0x82, 0x1f, 0x5b, 0xb0, 0x7c, 0x78, 0x4e, 0xc3, 0xb3, 0xa0, 0x20, 0x4f,
	0x69, 0x44, 0x28, 0xd6, 0x2d, 0xcf, 0xc4, 0x21, 0x9a, 0x79, 0x66, 0x0c, 0x8b, 0xe6, 0x25, 0xc3,
	0xa2, 0x75, 0xc9, 0xb0, 0x98, 0xbb, 0x64, 0x58, 0xb4, 0x27, 0x86, 0x45, 0x0f, 0x3a, 0x72, 0x7b,
	0x72, 0xc8, 0x48, 0x19, 0xe1, 0x76, 0x12, 0x94, 0xe1, 0xd9, 0xc1, 0x1e, 0xeb, 0x7e, 0xdb, 0x97,
	0x22, 0x5e, 0x36, 0xb6, 0x64, 0xb7, 0x89, 0x4f, 0x18, 0xa5, 0x60, 0x97, 0x9b, 0x14, 0xa1, 0x98,
	0x2c, 0x6c, 0xed, 0xec, 0x40, 0x3b, 0x2e, 0xc9, 0x10, 0x47, 0x0a, 0x56, 0xed, 0xee, 0xb4, 0xaa,
	0x19, 0xd5, 0xe9, 0x1f, 0xa0, 0x8b, 0xcf, 0x3d, 0x7b, 0x01, 0xb4, 0x99, 0x8c, 0xd9, 0x73, 0x9a,
	0x45, 0xe7, 0x61, 0x79, 0xb0, 0x27, 0x4a, 0xa7, 0x14, 0x55, 0xf6, 0xa6, 0x96, 0x7d, 0x0d, 0x5a,
	0x6f, 0xcb, 0x31, 0x2b, 0x5a, 0xdb, 0xc7, 0x25, 0x5e, 0x83, 0x9c, 0xc6, 0x21, 0xbf, 0x1d, 0x0d,
	0x9f, 0x0b, 0x5e, 0x04, 0xd7, 0x8d, 0x0d, 0x54, 0xd0, 0xfd, 0x02, 0x96, 0x73, 0xdd, 0xc0, 0xd2,
	0x2e, 0xde, 0xfb, 0x9b, 0xd5, 0x31, 0x7c, 0xd3, 0xd7, 0x23, 0xb0, 0x69, 0xd8, 0x25, 0xba, 0x9e,
	0xc0, 0x8a, 0xf1, 0x43, 0x09, 0x31, 0xcb, 0x2c, 0x13, 0xce, 0xde, 0xf7, 0x2d, 0x58, 0xda, 0x23,
	0x49, 0x3c, 0x22, 0x74, 0xfc, 0x65, 0xc6, 0x87, 0x60, 0x24, 0x64, 0xf5, 0xb0, 0x29, 0x0d, 0xd6,
	0x84, 0x92, 0xd3, 0xc3, 0xa7, 0xac, 0x74, 0x6d, 0x9f, 0x0b, 0x58, 0x6d, 0x8e, 0xa4, 0xa8, 0x82,
	0x9d, 0x52, 0x18, 0x98, 0x9c, 0x9b, 0xc0, 0xa4, 0xf2, 0xac, 0x80, 0xa7, 0x14, 0x06, 0x2a, 0xe7,
	0x27, 0x50, 0x89, 0xc3, 0x2f, 0x2b, 0x89, 0x18, 0x3a, 0x6c, 0xed, 0xfc, 0x57, 0x22, 0xa8, 0xc3,
	0x8a, 0x72, 0x67, 0x5a, 0x51, 0xf4, 0x23, 0x9b, 0x00, 0x1a, 0x5f, 0x00, 0xa0, 0x68, 0x12, 0x40,
	0xd1, 0x85, 0x00, 0xba, 0x09, 0x90, 0x61, 0x55, 0x49, 0xf4, 0xac, 0xc2, 0x91, 0xa6, 0x41, 0x3b,
	0x25, 0xe1, 0x28, 0xe6, 0xf6, 0x39, 0x6e, 0x57, 0x1a, 0xef, 0x3b, 0xd8, 0xd4, 0xf7, 0x55, 0xe1,
	0xea, 0x7f, 0x38, 0x65, 0x95, 0x5e, 0xc0, 0xea, 0xb6, 0xcd, 0xd9, 0x7c, 0xc3, 0xd3, 0x0b, 0x60,
	0x43, 0xb7, 0x4a, 0x4c, 0xfd, 0x1f, 0x96, 0xf5, 0x9f, 0x49, 0x48, 0xd9, 0x65, 0x30, 0x5d, 0xbd,
	0x5f, 0x9b, 0xb0, 0xf8, 0x24, 0x28, 0x4a, 0x42, 0x8f, 0xca, 0x2c, 0x7c, 0xa3, 0xcd, 0xfc, 0x36,
	0xce, 0x7c, 0x31, 0xcb, 0x9a, 0xd5, 0x2c, 0xf3, 0x26, 0x0e, 0xc7, 0xcb, 0x66, 0xe8, 0x10, 0x73,
	0x65, 0x56, 0x06, 0x89, 0xa8, 0x19, 0x17, 0xb4, 0x06, 0xc5, 0x11, 0x43, 0x8e, 0x6a, 0x50, 0x1c,
	0x4d, 0x10, 0xb4, 0xf9, 0x0f, 0x08, 0xda, 0x03, 0x89, 0x94, 0x85, 0xcb, 0xdf, 0x62, 0xed, 0x2c,
	0x26, 0x50, 0x62, 0x09, 0x14, 0xf6, 0x34, 0xd0, 0x38, 0x48, 0xd8, 0x29, 0x1b, 0xbe, 0x90, 0x70,
	0x9e, 0xe4, 0xb1, 0xe4, 0x7f, 0xb8, 0x9c, 0x20, 0x18, 0xad, 0x0f, 0x08, 0x86, 0x7a, 0xb0, 0xc4,
	0x73, 0xcc, 0x25, 0xef, 0x15, 0x6c, 0x68, 0xdb, 0xa8, 0x70, 0xb1, 0x0f, 0x8b, 0x43, 0xa5, 0x16,
	0xb0, 0xf8, 0xab, 0xc5, 0x41, 0x7c, 0xdd, 0xcf, 0x7b, 0x0d, 0x8e, 0x66, 0x93, 0x98, 0x78, 0x0c,
	0x4b, 0xda, 0x8f, 0x24, 0x24, 0xac, 0xa2, 0x1b, 0x8e, 0xde, 0x2f, 0x4d, 0xe8, 0xb2, 0xe5, 0x61,
	0x96, 0x31, 0xc6, 0x91, 0x67, 0x59, 0x52, 0x5d, 0x29, 0x21, 0xfd, 0xe1, 0x4f, 0xda, 0x16, 0x2c,
	0x32, 0xe2, 0x77, 0xc4, 0x3b, 0xc7, 0xf1, 0xa1, 0xab, 0x18, 0x6f, 0x4d, 0x23, 0x61, 0xe7, 0x4f,
	0x9b, 0x52, 0x68, 0xad, 0xea, 0xe8, 0xad, 0x52, 0x50, 0xed, 0x4e, 0x40, 0x95, 0x2d, 0x8e, 0xb2,
	0x24, 0x62, 0x7c, 0xb9, 0xed, 0x2b, 0x05, 0x5a, 0x29, 0x32, 0xac, 0x34, 0x4e, 0x07, 0x8c, 0x39,
	0xb7, 0x7d, 0xa5, 0xf0, 0x9e, 0xc3, 0x7a, 0x55, 0xbe, 0xaa, 0xf5, 0x0f, 0x90, 0xc8, 0x0a, 0xa5,
	0x68, 0xfc, 0x5f, 0xa6, 0x72, 0x8c, 0xca, 0x5b, 0xf9, 0x78, 0xc7, 0xb0, 0x56, 0xe9, 0x65, 0xcb,
	0x77, 0x00, 0xaa, 0x1f, 0xc8, 0x86, 0x5b, 0x44, 0xd5, 0x9c, 0xbc, 0x1f, 0x1a, 0xb0, 0x7c, 0x74,
	0x16, 0xe7, 0x79, 0x9c, 0x0e, 0xf6, 0xf1, 0xa7, 0xc8, 0x0f, 0xd8, 0x08, 0xac, 0x3a, 0x2e, 0xc5,
	0xba, 0x96, 0xe3, 0x2d, 0x63, 0x4c, 0x5e, 0xb4, 0x5c, 0xca, 0xd8, 0x3a, 0x76, 0x03, 0x45, 0x6b,
	0xf8, 0x4c, 0xd0, 0x55, 0xd8, 0x1c, 0x32, 0x62, 0x9f, 0x14, 0xbc, 0xed, 0x42, 0xc2, 0x97, 0xdb,
	0xd8, 0x9c, 0xfe, 0x72, 0x17, 0xba, 0xa1, 0xee, 0xe5, 0x36, 0xa3, 0x98, 0xbe, 0xf8, 0x72, 0x1b,
	0x76, 0xed, 0xe5, 0x36, 0x7e, 0x58, 0xfb, 0x72, 0x9b, 0x59, 0x26, 0x9c, 0xef, 0xfd, 0xd6, 0x83,
	0xee, 0x81, 0xfc, 0xad, 0x73, 0x04, 0x4b, 0x3e, 0x09, 0xa2, 0xea, 0xfb, 0xf4, 0xd6, 0xb4, 0xa0,
	0x82, 0x8b, 0xf7, 0x6a, 0x29, 0xa9, 0x77, 0x0d, 0x83, 0x1e, 0x05, 0x23, 0x52, 0x05, 0xad, 0xf5,
	0xe9, 0x4d, 0x4d, 0x2b, 0x38, 0xb9, 0x77, 0xcd, 0x79, 0x05, 0xab, 0x87, 0x34, 0x0b, 0x49, 0x51,
	0xa8, 0x8f, 0xe9, 0x69, 0x5e, 0x9c, 0x94, 0xf7, 0xfe, 0x5e, 0x97, 0x57, 0x94, 0xd8, 0xbb, 0xe6,
	0x04, 0xb0, 0xf2, 0x98, 0x94, 0x3b, 0x49, 0x52, 0x05, 0x9f, 0xfa, 0x8a, 0xe9, 0x1f, 0xf7, 0xb3,
	0xa4, 0x38, 0x86, 0x95, 0x63, 0x36, 0x46, 0x3e, 0x6f, 0x5d, 0x9e, 0xc3, 0xca, 0x1e, 0x49, 0x88,
	0x16, 0xb6, 0xb6, 0x87, 0x16, 0x51, 0x5f, 0xc3, 0x3a, 0xe2, 0xc2, 0xfc, 0x9e, 0xa8, 0x0d, 0x6c,
	0x47, 0x26, 0x79, 0x78, 0x44, 0x88, 0x19, 0xde, 0xce, 0xdb, 0x66, 0xf7, 0xa7, 0xb0, 0x29, 0xb0,
	0x62, 0x66, 0xa8, 0x03, 0xcc, 0x3f, 0xad, 0x76, 0xa0, 0x5a, 0xfa, 0x06, 0x36, 0x38, 0x6a, 0xcc,
	0x34, 0x76, 0xd0, 0x99, 0x35, 0xd9, 0xb7, 0xb0, 0xc1, 0xf1, 0x73, 0x55, 0x55, 0xfb, 0x9a, 0xb1,
	0x3c, 0x32, 0x99, 0xe0, 0x73, 0xc0, 0xe9, 0x25, 0xac, 0x21, 0x9c, 0x8c, 0x2f, 0x86, 0xda, 0xb8,
	0x56, 0x3c, 0x92, 0x07, 0x47, 0x30, 0x19, 0xc1, 0xad, 0x7c, 0x6d, 0x76, 0x1e, 0xc1, 0x86, 0x80,
	0x92, 0xf9, 0xb9, 0x53, 0x83, 0xa4, 0xbb, 0x36, 0xf9, 0x55, 0x6f, 0x63, 0x70, 0x38, 0x90, 0xec,
	0x0e, 0x61, 0xe0, 0x68, 0xc6, 0x54, 0xaf, 0xc1, 0xe1, 0x30, 0xba, 0x9a, 0x7a, 0x7d, 0x05, 0x0e,
	0x07, 0xd1, 0x6c, 0xbd, 0xb6, 0x82, 0xe7, 0x2a, 0x62, 0x48, 0xff, 0x48, 0xa8, 0x0d, 0x6b, 0xc3,
	0x3b, 0x79, 0x68, 0x44, 0x90, 0x1e, 0xda, 0xc6, 0xd3, 0x66, 0xd7, 0x27, 0xe0, 0x08, 0xfc, 0xe8,
	0xd1, 0xeb, 0xe0, 0x73, 0xc7, 0x22, 0xbb, 0x6a, 0xe9, 0x00, 0xd6, 0x39, 0x7a, 0xf4, 0x14, 0x76,
	0xe0, 0x99, 0x2d, 0xd1, 0x4b, 0x58, 0xe7, 0xd8, 0xb9, 0x8a, 0x4a, 0xbd, 0x80, 0x75, 0x8e, 0x9c,
	0x99, 0x3a, 0x6c, 0x11, 0xf8, 0x18, 0x96, 0x19, 0xc7, 0xa9, 0x3e, 0x26, 0x6a, 0x83, 0xd6, 0xb3,
	0x57, 0x1e, 0x96, 0xb1, 0x9c, 0x2a, 0x6c, 0xbd, 0x97, 0xcd, 0x6e, 0xbf, 0x81, 0x35, 0xc9, 0x73,
	0xaa, 0xc8, 0x75, 0x70, 0xd9, 0xae, 0xcd, 0xac, 0x7a, 0x18, 0xc2, 0xaa, 0x60, 0x3a, 0x55, 0x78,
	0x3b, 0xa8, 0xcc, 0x92, 0xe4, 0x05, 0xac, 0x0a, 0xae, 0xf3, 0x99, 0xab, 0x73, 0x0c, 0xab, 0x82,
	0xed, 0xd8, 0x77, 0xd3, 0x9e, 0xee, 0x98, 0x9f, 0x20, 0x1f, 0x4f, 0x77, 0x8c, 0x38, 0x8a, 0xee,
	0x98, 0xe1, 0xed, 0xbc, 0x67, 0xa3, 0x3b, 0x66, 0x86, 0x8f, 0xa6, 0x3b, 0x17, 0x7d, 0x87, 0xe8,
	0x74, 0xc7, 0x4c, 0xf3, 0x89, 0x74, 0x67, 0x4a, 0xb2, 0x8a, 0xee, 0x5c, 0x55, 0xd5, 0x2a, 0xba,
	0x33, 0x63, 0xd7, 0xeb, 0x43, 0x9f, 0xcc, 0xb3, 0x7f, 0x08, 0xef, 0xff, 0x1e, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x04, 0x8a, 0x04, 0x44, 0x1c, 0x00, 0x00,
}
